### ISSUE TITLE
Weak signature for shadowsocks-libev package.

### ISSUE THREAD

**Issue by fortuna** [shadowsocks/shadowsocks-libev#1124]
Please answer these questions before submitting your issue. Thanks!

### What version of shadowsocks-libev are you using?
2.4.0

### What operating system are you using?

Ubuntu 16.04.1 LTS

### What did you do?

I installed shadosocks-libev with these commands:
````
wget -O- http://shadowsocks.org/debian/1D27208A.gpg | apt-key add -
echo "deb http://shadowsocks.org/debian wheezy main" >> /etc/apt/sources.list
apt-get update && apt-get install -y shadowsocks-libev
````

### What did you expect to see?

A safe installation with no warnings.

### What did you see instead?

I got the warning:
`````
W: http://shadowsocks.org/debian/dists/wheezy/InRelease: Signature by key BA5A4D12BACB1AEF47F19BD31939D14B1D27208A uses weak digest algorithm (SHA1)
`````

This means a man-in-the-middle could deliver a malicious version of the package by forging the signature.

The release process should be updated to sign the package with a safer algorithm.

**Comment by madeye** [comment]
Forgot to update the install page on shadowsocks.org. Please follow the latest instructions to install debian package: https://github.com/shadowsocks/shadowsocks-libev#debian--ubuntu

**Comment by madeye** [comment]
Fixed via https://github.com/shadowsocks/shadowsocks-org/commit/b89f2f5edcba0078e123ec9795aadddda0d0804f

**Comment by fortuna** [comment]
I'm following the instructions you pointed out.
````
sudo sh -c 'printf "deb http://httpredir.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list'
sudo apt update
````

I now get the error:

````
Get:4 http://debian.csail.mit.edu/debian jessie-backports InRelease [166 kB]     
Err:4 http://debian.csail.mit.edu/debian jessie-backports InRelease
  The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553  NO_PUBKEY 7638D0442B90D010
W: GPG error: http://ftp-nyc.osuosl.org/debian jessie-backports InRelease: The following signatures couldn't be verified because the public key is not available: NO_PUBKEY 8B48AD6246925553  NO_PUBKEY 7638D0442B90D010
E: The repository 'http://httpredir.debian.org/debian jessie-backports InRelease' is not signed.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
````

Is this expected?
It seems to me it's better to have the previous weak signature than no signature.

**Comment by hosiet** [comment]
@fortuna This error has nothing to do with shadowsocks-libev. This should be the problem of Debian.

Please do `apt update && apt dist-upgrade` and try again. If such problem still exists, report the bug to Debian Project.

**Comment by fortuna** [comment]
@rogers0 , would you be the right person to look into this?

**Comment by rogers0** [comment]
@fortuna so you retried "apt update", and got the same result?

**Comment by fortuna** [comment]
I ran `apt update && apt dist-upgrade`.

Now when I run `apt update` I get:
````
root@e75530d80adc:/# apt update
Get:1 http://shadowsocks.org/debian wheezy InRelease [2523 B]
Hit:2 http://archive.ubuntu.com/ubuntu xenial InRelease  
Hit:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:4 http://archive.ubuntu.com/ubuntu xenial-security InRelease
Fetched 2523 B in 0s (4170 B/s)
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
W: http://shadowsocks.org/debian/dists/wheezy/InRelease: Signature by key BA5A4D12BACB1AEF47F19BD31939D14B1D27208A uses weak digest algorithm (SHA1)
````

**Comment by fortuna** [comment]
For what it's worth, the repository seems to have version 2.4.0-1 of shadowsocks-libev:
````
root@e75530d80adc:/# apt install shadowsocks-libev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
shadowsocks-libev is already the newest version (2.4.0-1).
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
````

**Comment by rogers0** [comment]
@fortuna so you're using ubuntu 16.04, you cannot use jessie-backports as apt repo, which is ONLY for debian jessie.

please refer: https://github.com/shadowsocks/shadowsocks-libev/issues/1095#issuecomment-274445199
to build your own deb.

**Comment by fortuna** [comment]
You are right. I've installed on debian jessie and got no warning.

It would be great if https://shadowsocks.org/en/download/servers.html had instructions on how to install on Ubuntu 16.04, since it's the latest LTS version. It only has instructions for Ubuntu 16.10+.

**Comment by madeye** [comment]
Try building the package from source code: https://github.com/shadowsocks/shadowsocks-libev#build-deb-package-from-source
